#ifndef ASTINSTRUCTION_H_INCLUDED
#define ASTINSTRUCTION_H_INCLUDED

enum AstInstructions
{
    ////////////////////
    AI_Push,
    AI_Pop,
    ////////////////////
    AI_Call,
    AI_If,
    AI_Return,
    AI_Continue,
    AI_Break,
    AI_Switch,
    AI_Case,
    AI_Default,
    AI_For,
    AI_While,
    ////////////////////
    AI_Plus,
    AI_Minus,
    AI_Inc,
    AI_Dec,
    ///////////////////
    AI_Add,
    AI_Sub,
    AI_Mul,
    AI_Div,
    AI_Mod,
    ///////////////////
    AI_And,
    AI_Or,
    AI_Not,
    ///////////////////
    AI_Equal,
    AI_NotEqual,
    AI_LessEqual,
    AI_Less,
    AI_MoreEqual,
    AI_More,
    //////////////////
    AI_BitAnd,
    AI_BitOr,
    AI_BitXor,
    AI_BitNot,
    AI_ShiftLeft,
    AI_ShiftRight,
    /////////////////////
    AI_As,
    AI_To,
    AI_New,
    AI_Cast,
    /////////////////////////
    AI_Assign,
    AI_AddAssign,
    AI_SubAssign,
    AI_MulAssign,
    AI_DivAssign,
    AI_ModAssign,
    AI_BitAndAssign,
    AI_BitOrAssign,
    AI_BitXorAssign,
    AI_ShiftLeftAssign,
    AI_ShiftRightAssign,
    /////////////////////////////////
    AI_Block,
    AI_Declare,
    AI_Access,
};

#endif // ASTINSTRUCTION_H_INCLUDED
